version: '3.7'

services:
  server:
    container_name: server
    build:
      context: ./node_server
      dockerfile: Dockerfile
    volumes:
      - './node_server:/app'
      - '/app/node_modules'
      - '/app/dist'
    ports:
      - 5500:5500
  react:
    container_name: react
    build:
      context: ./react_app
      dockerfile: Dockerfile
    volumes:
      - './react_app:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - server  